import prisma from "../../config/prisma.js";
import { AppError } from "../../utils/AppError.js";
import { HTTP_STATUS } from "../../constants/http.js";
import { paginationParams } from "../../utils/pagination.js";
import { containsInsensitive } from "../../utils/search.js";
import { transaction } from "../../utils/transaction.js";
const ASSET_INCLUDE = { dataSource: { select: { id: true, name: true, provider: true } }, domain: true, owners: true, tags: true, schemas: { include: { columns: { orderBy: { ordinal: "asc" } } } } };
async function scope(userId, projectId, workspaceId) { const [project, workspace] = await transaction([prisma.project.findFirst({ where: { id: projectId, ownerId: userId } }), prisma.workspace.findFirst({ where: { id: workspaceId, ownerId: userId } })]); if (!project || !workspace) throw new AppError("Project or workspace was not found or is not accessible.", HTTP_STATUS.FORBIDDEN); }
async function assetScope(id, userId) { const asset = await prisma.metadataAsset.findUnique({ where: { id } }); if (!asset) throw new AppError("Metadata asset not found.", HTTP_STATUS.NOT_FOUND); await scope(userId, asset.projectId, asset.workspaceId); return asset; }
async function assertWorkspaceEntity(model, ids, workspaceId) { if (!ids?.length) return; const count = await model.count({ where: { id: { in: ids }, workspaceId } }); if (count !== ids.length) throw new AppError("Referenced metadata entities must belong to the selected workspace.", HTTP_STATUS.UNPROCESSABLE_ENTITY); }
function assetData(data) { const { ownerIds, tagIds, schemas, ...scalar } = data; return { ...scalar, ...(ownerIds && { owners: { set: ownerIds.map((id) => ({ id })) } }), ...(tagIds && { tags: { set: tagIds.map((id) => ({ id })) } }), ...(schemas && { schemas: { create: schemas.map(({ columns = [], ...item }) => ({ ...item, columns: { create: columns } })) } }) }; }
export async function createAsset(userId, data) { await scope(userId, data.projectId, data.workspaceId); await Promise.all([assertWorkspaceEntity(prisma.metadataOwner, data.ownerIds, data.workspaceId), assertWorkspaceEntity(prisma.metadataTag, data.tagIds, data.workspaceId), assertWorkspaceEntity(prisma.metadataDomain, data.domainId ? [data.domainId] : [], data.workspaceId)]); if (data.dataSourceId) { const ds = await prisma.dataSource.findFirst({ where: { id: data.dataSourceId, projectId: data.projectId, workspaceId: data.workspaceId } }); if (!ds) throw new AppError("Data source is outside the selected scope.", HTTP_STATUS.UNPROCESSABLE_ENTITY); } return prisma.metadataAsset.create({ data: assetData(data), include: ASSET_INCLUDE }); }
export async function listAssets(userId, filters) { const { page, limit, q, projectId, workspaceId } = filters; if (projectId || workspaceId) { if (!projectId || !workspaceId) throw new AppError("projectId and workspaceId must be supplied together.", HTTP_STATUS.UNPROCESSABLE_ENTITY); await scope(userId, projectId, workspaceId); } const where = { ...(projectId ? { projectId, workspaceId } : { project: { ownerId: userId } }), ...(q && { OR: [{ name: containsInsensitive(q) }, { description: containsInsensitive(q) }, { qualifiedName: containsInsensitive(q) }] }) }; const pg = paginationParams({ page, limit }); const [items, total] = await transaction([prisma.metadataAsset.findMany({ where, include: ASSET_INCLUDE, orderBy: { updatedAt: "desc" }, skip: pg.skip, take: pg.take }), prisma.metadataAsset.count({ where })]); return { items, total, pagination: pg }; }
export async function getAsset(id, userId) { await assetScope(id, userId); return prisma.metadataAsset.findUnique({ where: { id }, include: ASSET_INCLUDE }); }
export async function updateAsset(id, userId, data) { const asset = await assetScope(id, userId); await Promise.all([assertWorkspaceEntity(prisma.metadataOwner, data.ownerIds, asset.workspaceId), assertWorkspaceEntity(prisma.metadataTag, data.tagIds, asset.workspaceId), assertWorkspaceEntity(prisma.metadataDomain, data.domainId ? [data.domainId] : [], asset.workspaceId)]); if (data.dataSourceId) { const dataSource = await prisma.dataSource.findFirst({ where: { id: data.dataSourceId, projectId: asset.projectId, workspaceId: asset.workspaceId } }); if (!dataSource) throw new AppError("Data source is outside the selected scope.", HTTP_STATUS.UNPROCESSABLE_ENTITY); } return prisma.metadataAsset.update({ where: { id }, data: assetData(data), include: ASSET_INCLUDE }); }
export async function deleteAsset(id, userId) { await assetScope(id, userId); await prisma.metadataAsset.delete({ where: { id } }); }
const ENTITY_MODELS = { owners: prisma.metadataOwner, tags: prisma.metadataTag, domains: prisma.metadataDomain };
export async function createEntity(kind, userId, data) { const workspace = await prisma.workspace.findFirst({ where: { id: data.workspaceId, ownerId: userId } }); if (!workspace) throw new AppError("Workspace was not found or is not accessible.", HTTP_STATUS.FORBIDDEN); const model = ENTITY_MODELS[kind]; return model.create({ data: kind === "owners" ? { workspaceId: data.workspaceId, name: data.name, email: data.email } : { workspaceId: data.workspaceId, name: data.name, description: data.description } }); }
export async function listEntities(kind, userId, workspaceId) { const model = ENTITY_MODELS[kind]; return model.findMany({ where: { workspace: { ownerId: userId }, ...(workspaceId && { workspaceId }) }, orderBy: { name: "asc" } }); }
export async function updateEntity(kind, id, userId, data) { const model = ENTITY_MODELS[kind]; const item = await model.findFirst({ where: { id, workspace: { ownerId: userId } } }); if (!item) throw new AppError("Metadata entity not found.", HTTP_STATUS.NOT_FOUND); const updateData = kind === "owners" ? { ...(data.name !== undefined && { name: data.name }), ...(data.email !== undefined && { email: data.email }) } : { ...(data.name !== undefined && { name: data.name }), ...(data.description !== undefined && { description: data.description }) }; return model.update({ where: { id }, data: updateData }); }
export async function deleteEntity(kind, id, userId) { const model = ENTITY_MODELS[kind]; const item = await model.findFirst({ where: { id, workspace: { ownerId: userId } } }); if (!item) throw new AppError("Metadata entity not found.", HTTP_STATUS.NOT_FOUND); await model.delete({ where: { id } }); }
