// src/integrations/github/github.service.js
// ============================================================
// Incident -> Pull Request flow.
//
// createIncidentPullRequest is the only entry point: it verifies the
// fix has been explicitly approved (never auto-approved), resolves
// GitHub credentials for the incident's project, then creates a
// branch, writes the fix's proposed files, and opens a PR — never
// merges.
//
// Credential resolution (Phase 4A): prefer the GitHub repository
// connected to the incident's project (Project -> GitHubRepository ->
// GitHubConnection); fall back to the legacy global
// GITHUB_TOKEN/OWNER/REPO env vars when no project-level connection
// exists. If neither is available, throws a clean, actionable AppError
// (503) rather than crashing; the fix stays APPROVED and PR creation
// can be retried via POST /investigations/:id/fix/pr once connected.
//
// The incident is NOT marked RESOLVED here — only once GitHub confirms
// (via the signed webhook, see github.webhook.js) that the PR was
// actually merged. Creating a PR is a proposal becoming visible for
// review, not a resolution.
// ============================================================

import { AppError } from "../../utils/AppError.js";
import { HTTP_STATUS } from "../../constants/http.js";
import { env } from "../../config/env.js";
import prisma from "../../config/prisma.js";
import { decrypt } from "../../utils/encryption.js";
import { getInvestigation } from "../../modules/investigation/investigation.service.js";
import { logEvent } from "../../modules/investigation/incident-event.service.js";
import * as client from "./github.client.js";

function buildPrBody(incident) {
  const fix = incident.proposedFix;
  const impact = incident.impact;
  const validation = incident.fixValidation;
  const rootCause = incident.evidence?.rootCause;

  const validationSection = validation
    ? [`Valid: ${validation.valid}`, `Risk: ${validation.risk}`, ...(validation.warnings?.length ? ["Warnings:", ...validation.warnings.map((w) => `- ${w}`)] : ["No warnings."])].join("\n")
    : "Not recorded.";

  return [
    "## Root Cause",
    "",
    rootCause?.description ?? "Unknown",
    "",
    "## Impact",
    "",
    `- ${impact?.categories?.dashboards ?? 0} dashboard(s)`,
    `- ${impact?.categories?.datasets ?? 0} dataset(s)`,
    `- ${impact?.categories?.mlModels ?? 0} ML model(s)`,
    `- ${impact?.categories?.pipelines ?? 0} pipeline(s)`,
    "",
    `Risk: ${fix?.risk ?? "UNKNOWN"}`,
    "",
    "## Proposed Fix",
    "",
    fix?.summary ?? "",
    "",
    "```sql",
    fix?.sql ?? "-- no SQL generated",
    "```",
    "",
    "## Validation",
    "",
    validationSection,
    "",
    "## Avenor Investigation",
    "",
    `Investigation ID: ${incident.id}`,
    `Report: GET /api/v1/investigations/${incident.id}/report`,
    "",
    "---",
    "Generated by Avenor AI DataOps Engineer.",
  ].join("\n");
}

/**
 * Resolves GitHub credentials for an incident's project. Prefers the
 * project's connected repository; falls back to `undefined` (global
 * env) when none is connected. Defends against a repository somehow
 * being linked to a connection that isn't the requesting user's own —
 * this should be structurally impossible (POST /github/repositories/:id/select
 * already checks both sides), but the credential boundary is exactly
 * the place worth double-checking.
 */
async function resolveGithubContext(incident, userId) {
  const project = await prisma.project.findUnique({
    where: { id: incident.projectId },
    include: { githubRepository: { include: { connection: true } } },
  });
  const repository = project?.githubRepository;
  if (!repository) return { ctx: undefined, baseBranch: env.GITHUB_DEFAULT_BRANCH };

  if (repository.connection.userId !== userId || repository.connection.status !== "ACTIVE") {
    return { ctx: undefined, baseBranch: env.GITHUB_DEFAULT_BRANCH };
  }

  return {
    ctx: { token: decrypt(repository.connection.encryptedAccessToken), owner: repository.owner, repo: repository.name },
    baseBranch: project.githubBranch || repository.defaultBranch || env.GITHUB_DEFAULT_BRANCH,
    fullName: repository.fullName,
  };
}

/**
 * @param {string} investigationId
 * @param {string} userId
 * @returns {Promise<import('./github.types.js').GitHubPullRequestResult>}
 */
export async function createIncidentPullRequest(investigationId, userId) {
  const incident = await getInvestigation(investigationId, userId);

  if (!incident.proposedFix) throw new AppError("No fix has been proposed for this investigation.", HTTP_STATUS.UNPROCESSABLE_ENTITY);
  if (incident.fixApprovalStatus !== "APPROVED") throw new AppError("Fix must be explicitly approved (POST /investigations/:id/fix/approve) before a pull request can be created.", HTTP_STATUS.UNPROCESSABLE_ENTITY);

  const { ctx, baseBranch, fullName } = await resolveGithubContext(incident, userId);

  if (!client.isConfigured(ctx)) {
    throw new AppError(
      "GitHub repository is not connected to this project. Connect a GitHub repository via POST /api/v1/github/connect before creating a pull request (or configure GITHUB_TOKEN/GITHUB_OWNER/GITHUB_REPO as a fallback).",
      HTTP_STATUS.SERVICE_UNAVAILABLE
    );
  }

  const branch = `avenor/incident-${incident.id.slice(0, 8)}`;

  const baseRef = await client.getBranchRef(baseBranch, ctx);
  try {
    await client.createBranch(branch, baseRef.object.sha, ctx);
  } catch (err) {
    // 422 = ref already exists — safe to reuse (idempotent retry).
    if (!(err instanceof client.GitHubApiError) || err.status !== 422) throw err;
  }
  await logEvent(investigationId, "GITHUB_BRANCH_CREATED", `Created branch "${branch}" from "${baseBranch}".`, { branch });

  const files = incident.proposedFix.files?.length ? incident.proposedFix.files : [{ path: `avenor/incidents/${incident.id}.sql`, content: incident.proposedFix.sql ?? "-- no SQL generated" }];
  for (const file of files) {
    const existing = await client.getFileContent(file.path, branch, ctx);
    await client.putFileContent(file.path, { message: `fix: ${incident.title}`, content: file.content, branch, sha: existing?.sha }, ctx);
  }

  const pr = await client.createPullRequest({ title: `fix: resolve ${incident.title} incident`, head: branch, base: baseBranch, body: buildPrBody(incident) }, ctx);

  const githubPr = { branch, prNumber: pr.number, prUrl: pr.html_url, fullName: fullName ?? `${env.GITHUB_OWNER}/${env.GITHUB_REPO}` };
  await logEvent(investigationId, "GITHUB_PR_CREATED", `Opened PR #${pr.number}: ${pr.html_url}`, githubPr);

  await prisma.dataIncident.update({ where: { id: investigationId }, data: { githubPr, fixApprovalStatus: "PR_CREATED" } });

  return githubPr;
}
