export const ROUTES = {
  landing: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  investigations: "/investigations",
  newInvestigation: "/investigations/new",
  investigationDetail: (id: string) => `/investigations/${id}`,
  metadata: "/metadata",
  metadataAsset: (id: string) => `/metadata/${id}`,
  lineage: "/lineage",
  dataSources: "/datasources",
  documents: "/documents",
  projects: "/projects",
  workspaces: "/workspaces",
  github: "/github",
  settings: "/settings",
} as const;
